(function(){
'use strict';
const GRACE_DAYS=20,DAY=86400000,HOUR=3600000;
const TABLES={schools:'schools',codes:'school_activation_codes',devices:'school_activated_devices'};
const state={client:null,schools:[],codes:[],devices:[],selected:null};
const $=id=>document.getElementById(id),txt=v=>String(v??'');
const esc=v=>txt(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function status(message,error=false){const el=$('status');el.textContent=message;el.className=error?'notice error':'notice'}
function client(){if(state.client)return state.client;if(!window.supabase||!window.SCHOOL_TIMER_SUPABASE_URL||!window.SCHOOL_TIMER_SUPABASE_ANON_KEY)return null;state.client=window.supabase.createClient(window.SCHOOL_TIMER_SUPABASE_URL,window.SCHOOL_TIMER_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return state.client}
function isDemo(s){const h=`${s?.school_slug||''} ${s?.school_name||''}`.toLowerCase();return /(^|[\s_-])(sample|demo|test|preview|default|example|trial)([\s_-]|$)/i.test(h)||/(تجريب|اختبار|افتراضي|نموذج|مثال)/.test(h)}
function realSchools(){return state.schools.filter(s=>s&&s.school_slug&&!isDemo(s)).sort((a,b)=>Number(b.is_active!==false)-Number(a.is_active!==false)||txt(a.school_name).localeCompare(txt(b.school_name),'ar'))}
function date(v){if(!v)return null;const d=new Date(v);return Number.isFinite(d.getTime())?d:null}
function format(v){const d=date(v);return d?new Intl.DateTimeFormat('ar-OM',{dateStyle:'medium',timeStyle:'short'}).format(d):'—'}
function today(v){const d=date(v),n=new Date();return !!d&&d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function grace(v){const d=date(v);if(!d)return{label:'غير متوفر',cls:'expired'};const left=GRACE_DAYS*DAY-Math.max(0,Date.now()-d.getTime());if(left<=0)return{label:'انتهت المهلة',cls:'expired'};const days=Math.floor(left/DAY),hours=Math.floor(left%DAY/HOUR);return{label:days?`${days} يوم و${hours} ساعة`:`${Math.max(1,hours)} ساعة`,cls:left<=3*DAY?'warn':''}}
function codeRows(slug){return state.codes.filter(x=>x.school_slug===slug)}
function deviceRows(slug){return state.devices.filter(x=>x.school_slug===slug)}
function renderStats(){const slugs=new Set(realSchools().map(s=>s.school_slug));const codes=state.codes.filter(x=>slugs.has(x.school_slug)&&x.is_active!==false);const devices=state.devices.filter(x=>slugs.has(x.school_slug)&&x.is_active!==false);$('schoolsStat').textContent=slugs.size;$('codesStat').textContent=codes.length;$('devicesStat').textContent=devices.length;$('todayStat').textContent=devices.filter(x=>today(x.last_seen_at)).length;$('schoolsCount').textContent=slugs.size}
function renderSchools(){const q=txt($('search').value).trim().toLowerCase();const rows=realSchools().filter(s=>!q||`${s.school_name||''} ${s.school_slug||''} ${s.governorate||''} ${s.wilayat||''}`.toLowerCase().includes(q));$('schoolsList').innerHTML=rows.length?rows.map(s=>`<article class="school ${state.selected===s.school_slug?'active':''}" data-slug="${esc(s.school_slug)}"><div class="school-top"><div class="school-name">${esc(s.school_name||s.school_slug)}</div><span class="badge ${s.is_active===false?'off':'on'}">${s.is_active===false?'موقوفة':'مفعلة'}</span></div><div class="meta">${esc(s.school_slug)}<br>${codeRows(s.school_slug).filter(x=>x.is_active!==false).length} كود نشط · ${deviceRows(s.school_slug).filter(x=>x.is_active!==false).length} جهاز مفعل</div></article>`).join(''):'<div class="empty">لا توجد مدارس حقيقية مطابقة.</div>'}
function renderDetails(){const school=realSchools().find(s=>s.school_slug===state.selected);if(!school){$('empty').hidden=false;$('details').hidden=true;return}$('empty').hidden=true;$('details').hidden=false;$('schoolName').textContent=school.school_name||school.school_slug;$('schoolMeta').textContent=[school.school_slug,school.governorate,school.wilayat].filter(Boolean).join(' · ');const codes=codeRows(school.school_slug).sort((a,b)=>Number(b.is_active!==false)-Number(a.is_active!==false));$('codesList').innerHTML=codes.length?codes.map(c=>`<article class="card"><div class="row"><div class="code">${esc(c.activation_code||'—')}</div><span class="badge ${c.is_active===false?'off':'on'}">${c.is_active===false?'موقوف':'نشط'}</span></div><div class="small">الأجهزة: ${deviceRows(school.school_slug).filter(d=>d.activation_code===c.activation_code&&d.is_active!==false).length} / ${Number(c.max_devices||1)}<br>تاريخ الإنشاء: ${format(c.created_at)}<br>الانتهاء: ${c.expires_at?format(c.expires_at):'بدون انتهاء'}</div></article>`).join(''):'<div class="empty">لا توجد أكواد تفعيل.</div>';const devices=deviceRows(school.school_slug).sort((a,b)=>txt(b.last_seen_at).localeCompare(txt(a.last_seen_at)));$('devicesBody').innerHTML=devices.length?devices.map(d=>{const g=grace(d.last_seen_at);return`<tr><td><div class="device">${esc(d.device_name||'جهاز بدون اسم')}</div><div class="device-id">${esc(d.device_id||'—')}</div></td><td><span class="badge ${d.is_active===false?'off':'on'}">${d.is_active===false?'موقوف':'مصرح'}</span></td><td>${format(d.last_seen_at)}</td><td><span class="grace ${g.cls}">${d.is_active===false?'الجهاز موقوف':g.label}</span></td><td>${esc(d.app_version||'—')}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">لا توجد أجهزة مسجلة.</td></tr>'}
function select(slug){if(!realSchools().some(s=>s.school_slug===slug))return;state.selected=slug;renderSchools();renderDetails()}
async function load(){const button=$('refreshBtn');button.disabled=true;status('جارٍ تحميل بيانات برنامج Windows…');try{const db=client();if(!db)throw new Error('تعذر تحميل اتصال Supabase.');const [s,c,d]=await Promise.all([db.from(TABLES.schools).select('*').order('school_name',{ascending:true}),db.from(TABLES.codes).select('*'),db.from(TABLES.devices).select('*')]);if(s.error)throw s.error;if(c.error)throw c.error;if(d.error)throw d.error;state.schools=s.data||[];state.codes=c.data||[];state.devices=d.data||[];const rows=realSchools();if(!rows.some(x=>x.school_slug===state.selected))state.selected=rows[0]?.school_slug||null;renderStats();renderSchools();renderDetails();status('تم تحميل البيانات الحقيقية بنجاح.')}catch(e){console.error(e);status(`تعذر تحميل البيانات: ${e.message||e}`,true);$('schoolsList').innerHTML='<div class="empty">تعذر تحميل المدارس.</div>';state.selected=null;renderDetails()}finally{button.disabled=false}}
function init(){$('refreshBtn').addEventListener('click',load);$('search').addEventListener('input',renderSchools);$('schoolsList').addEventListener('click',e=>{const item=e.target.closest('[data-slug]');if(item)select(item.dataset.slug)});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
