-- Windows central audio management — version 2 upgrade.
-- Run after database/windows_audio_central.sql.
-- Scope: audio releases, weekly guidance rotation, scheduled campaigns,
-- and the school manager's audio-profile preference.
-- It does not alter timer schedules, viewer data, or school-facing display tables.

begin;

do $$
begin
  if to_regclass('public.windows_audio_releases') is null then
    raise exception 'Run database/windows_audio_central.sql before this v2 upgrade';
  end if;
end;
$$;

-- Each audience has an independent draft/published release stream.
alter table public.windows_audio_releases
  add column if not exists audience_key text;

update public.windows_audio_releases
set audience_key = 'boys'
where audience_key is null;

alter table public.windows_audio_releases
  alter column audience_key set default 'boys',
  alter column audience_key set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'windows_audio_releases_audience_key_check'
      and conrelid = 'public.windows_audio_releases'::regclass
  ) then
    alter table public.windows_audio_releases
      add constraint windows_audio_releases_audience_key_check
      check (audience_key in ('boys', 'girls'));
  end if;
end;
$$;

drop index if exists public.windows_audio_single_published_idx;

create unique index if not exists windows_audio_single_published_audience_idx
  on public.windows_audio_releases(audience_key)
  where status = 'published';

create table if not exists public.windows_audio_channels (
  audience_key text primary key
    check (audience_key in ('boys', 'girls')),
  active_release_id uuid references public.windows_audio_releases(id) on delete set null,
  default_profile_key text not null default 'end_only'
    check (default_profile_key in ('end_only', 'start_and_end')),
  rotation_anchor_sunday date not null default date '2026-07-12',
  updated_by uuid default auth.uid(),
  updated_at timestamptz not null default now()
);

insert into public.windows_audio_channels (audience_key)
values ('boys'), ('girls')
on conflict (audience_key) do nothing;

-- Preserve the already published v1 release as the boys release.
update public.windows_audio_channels channel
set active_release_id = settings.active_release_id,
    default_profile_key = settings.default_profile_key,
    updated_at = now()
from public.windows_audio_settings settings
where channel.audience_key = 'boys'
  and channel.active_release_id is null
  and settings.id = 1
  and settings.active_release_id is not null;

alter table public.windows_school_audio_profiles
  add column if not exists updated_source text not null default 'programmer',
  add column if not exists manager_updated_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'windows_school_audio_profiles_source_check'
      and conrelid = 'public.windows_school_audio_profiles'::regclass
  ) then
    alter table public.windows_school_audio_profiles
      add constraint windows_school_audio_profiles_source_check
      check (updated_source in ('programmer', 'school_manager'));
  end if;
end;
$$;

create table if not exists public.windows_audio_campaigns (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(btrim(title)) between 2 and 140),
  audience_key text not null default 'all'
    check (audience_key in ('all', 'boys', 'girls')),
  play_slot text not null default 'after_assembly'
    check (play_slot in ('after_assembly', 'before_first_period', 'after_break', 'end_of_day')),
  starts_on date not null,
  ends_on date not null,
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null default 'audio/mpeg',
  file_size_bytes bigint not null check (file_size_bytes > 0),
  duration_seconds numeric(10,3) check (duration_seconds is null or duration_seconds > 0),
  checksum_sha256 text check (checksum_sha256 is null or checksum_sha256 ~ '^[0-9a-f]{64}$'),
  max_plays_per_day smallint not null default 1 check (max_plays_per_day between 1 and 3),
  is_active boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on)
);

create index if not exists windows_audio_campaigns_active_idx
  on public.windows_audio_campaigns(is_active, starts_on, ends_on, audience_key);

create table if not exists public.windows_audio_audit_log (
  id bigint generated by default as identity primary key,
  actor_type text not null check (actor_type in ('programmer', 'school_manager', 'system')),
  action text not null,
  school_slug text,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists windows_audio_audit_created_idx
  on public.windows_audio_audit_log(created_at desc);

drop trigger if exists windows_audio_channels_touch on public.windows_audio_channels;
create trigger windows_audio_channels_touch
before update on public.windows_audio_channels
for each row execute function public.touch_windows_audio_updated_at();

drop trigger if exists windows_audio_campaigns_touch on public.windows_audio_campaigns;
create trigger windows_audio_campaigns_touch
before update on public.windows_audio_campaigns
for each row execute function public.touch_windows_audio_updated_at();

alter table public.windows_audio_channels enable row level security;
alter table public.windows_audio_campaigns enable row level security;
alter table public.windows_audio_audit_log enable row level security;

drop policy if exists windows_audio_channels_read on public.windows_audio_channels;
create policy windows_audio_channels_read
on public.windows_audio_channels
for select
to anon, authenticated
using (true);

drop policy if exists windows_audio_channels_programmer_write on public.windows_audio_channels;
create policy windows_audio_channels_programmer_write
on public.windows_audio_channels
for all
to authenticated
using (public.is_windows_programmer())
with check (public.is_windows_programmer());

drop policy if exists windows_audio_campaigns_read on public.windows_audio_campaigns;
create policy windows_audio_campaigns_read
on public.windows_audio_campaigns
for select
to anon, authenticated
using (
  public.is_windows_programmer()
  or (
    is_active
    and (now() at time zone 'Asia/Muscat')::date between starts_on and ends_on
  )
);

drop policy if exists windows_audio_campaigns_programmer_write on public.windows_audio_campaigns;
create policy windows_audio_campaigns_programmer_write
on public.windows_audio_campaigns
for all
to authenticated
using (public.is_windows_programmer())
with check (public.is_windows_programmer());

drop policy if exists windows_audio_audit_programmer_read on public.windows_audio_audit_log;
create policy windows_audio_audit_programmer_read
on public.windows_audio_audit_log
for select
to authenticated
using (public.is_windows_programmer());

drop policy if exists windows_audio_audit_programmer_write on public.windows_audio_audit_log;
create policy windows_audio_audit_programmer_write
on public.windows_audio_audit_log
for insert
to authenticated
with check (public.is_windows_programmer());

grant select on public.windows_audio_channels to anon, authenticated;
grant insert, update, delete on public.windows_audio_channels to authenticated;
grant select on public.windows_audio_campaigns to anon, authenticated;
grant insert, update, delete on public.windows_audio_campaigns to authenticated;
grant select on public.windows_audio_audit_log to authenticated;
grant insert on public.windows_audio_audit_log to authenticated;
grant usage, select on sequence public.windows_audio_audit_log_id_seq to authenticated;

create or replace function public.windows_school_audience(p_school_slug text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when lower(concat_ws(' ', school.school_type, school.school_name))
      ~ '(بنات|إناث|اناث|female|girls)'
      then 'girls'
    else 'boys'
  end
  from public.schools school
  where school.school_slug = p_school_slug
  limit 1;
$$;

create or replace function public.windows_audio_rotation(
  p_manifest jsonb,
  p_reference_date date default ((now() at time zone 'Asia/Muscat')::date)
)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  pool jsonb;
  pool_size integer;
  anchor_sunday date;
  current_sunday date;
  week_index integer;
  first_index integer;
  selected_keys jsonb;
begin
  pool := p_manifest #> '{central_config,awareness_sequence}';
  if pool is null or jsonb_typeof(pool) <> 'array' or jsonb_array_length(pool) < 2 then
    return jsonb_build_object('available', false, 'selected_asset_keys', '[]'::jsonb);
  end if;

  pool_size := jsonb_array_length(pool);
  current_sunday := p_reference_date - extract(dow from p_reference_date)::integer;

  begin
    anchor_sunday := (p_manifest #>> '{central_config,rotation_anchor_sunday}')::date;
  exception when others then
    anchor_sunday := current_sunday;
  end;
  anchor_sunday := coalesce(anchor_sunday, current_sunday);

  week_index := greatest(0, ((current_sunday - anchor_sunday) / 7));
  first_index := case when pool_size = 2 then 0 else mod(week_index * 2, pool_size) end;
  selected_keys := jsonb_build_array(
    pool ->> first_index,
    pool ->> mod(first_index + 1, pool_size)
  );

  return jsonb_build_object(
    'available', true,
    'rotation_enabled', pool_size > 2,
    'pool_size', pool_size,
    'week_index', week_index,
    'week_starts_on', current_sunday,
    'next_rotation_on', current_sunday + 7,
    'selected_asset_keys', selected_keys
  );
end;
$$;

create or replace function public.publish_windows_audio_release(p_release_id uuid)
returns public.windows_audio_releases
language plpgsql
security definer
set search_path = public
as $$
declare
  target_release public.windows_audio_releases;
  awareness_sequence jsonb;
  selected_default_profile text;
  selected_count integer;
  distinct_count integer;
  required_missing integer;
  current_sunday date;
  updated_manifest jsonb;
begin
  if not public.is_windows_programmer() then
    raise exception 'Not authorized to publish Windows audio releases';
  end if;

  select * into target_release
  from public.windows_audio_releases
  where id = p_release_id
  for update;

  if target_release.id is null then
    raise exception 'Audio release was not found';
  end if;
  if target_release.status <> 'draft' then
    raise exception 'Only a draft release can be published';
  end if;
  if target_release.audience_key not in ('boys', 'girls') then
    raise exception 'The target school audience is invalid';
  end if;

  awareness_sequence := target_release.manifest #> '{central_config,awareness_sequence}';
  if awareness_sequence is null or jsonb_typeof(awareness_sequence) <> 'array' then
    raise exception 'The guidance pool is missing';
  end if;

  selected_count := jsonb_array_length(awareness_sequence);
  select count(distinct selected.asset_key) into distinct_count
  from jsonb_array_elements_text(awareness_sequence) selected(asset_key);

  if selected_count < 2 or selected_count > 50 or distinct_count <> selected_count then
    raise exception 'Select between 2 and 50 different guidance clips';
  end if;

  selected_default_profile := target_release.manifest #>> '{central_config,default_profile}';
  if selected_default_profile is null
     or selected_default_profile not in ('end_only', 'start_and_end') then
    raise exception 'The default audio profile is invalid';
  end if;

  if exists (
    select 1
    from jsonb_array_elements_text(awareness_sequence) selected(asset_key)
    where not exists (
      select 1
      from public.windows_audio_assets asset
      where asset.release_id = p_release_id
        and asset.asset_key = selected.asset_key
        and asset.kind = 'guidance'
        and asset.is_active
    )
  ) then
    raise exception 'A selected guidance clip is missing or inactive';
  end if;

  select count(*) into required_missing
  from (
    values
      ('assembly_start'), ('break_start'), ('break_end'),
      ('period_01_start'), ('period_02_start'), ('period_03_start'), ('period_04_start'),
      ('period_05_start'), ('period_06_start'), ('period_07_start'), ('period_08_start'),
      ('period_01_end'), ('period_02_end'), ('period_03_end'), ('period_04_end'),
      ('period_05_end'), ('period_06_end'), ('period_07_end'), ('period_08_end')
  ) as required(asset_key)
  where not exists (
    select 1
    from public.windows_audio_assets asset
    where asset.release_id = p_release_id
      and asset.asset_key = required.asset_key
      and asset.kind = 'system_event'
  );

  if required_missing > 0 then
    raise exception 'The release is missing % required system audio files', required_missing;
  end if;

  current_sunday := (now() at time zone 'Asia/Muscat')::date
    - extract(dow from (now() at time zone 'Asia/Muscat')::date)::integer;

  updated_manifest := jsonb_set(
    target_release.manifest,
    '{central_config,rotation_anchor_sunday}',
    to_jsonb(current_sunday::text),
    true
  );
  updated_manifest := jsonb_set(
    updated_manifest,
    '{central_config,awareness_rotation}',
    to_jsonb(selected_count > 2),
    true
  );
  updated_manifest := jsonb_set(
    updated_manifest,
    '{central_config,week_starts_on}',
    to_jsonb('sunday'::text),
    true
  );

  update public.windows_audio_releases
  set status = 'archived'
  where status = 'published'
    and audience_key = target_release.audience_key;

  update public.windows_audio_releases
  set status = 'published',
      published_at = now(),
      manifest = updated_manifest
  where id = p_release_id
  returning * into target_release;

  insert into public.windows_audio_channels (
    audience_key, active_release_id, default_profile_key,
    rotation_anchor_sunday, updated_by
  ) values (
    target_release.audience_key, p_release_id, selected_default_profile,
    current_sunday, auth.uid()
  )
  on conflict (audience_key) do update
  set active_release_id = excluded.active_release_id,
      default_profile_key = excluded.default_profile_key,
      rotation_anchor_sunday = excluded.rotation_anchor_sunday,
      updated_by = excluded.updated_by,
      updated_at = now();

  -- Keep the original v1 settings usable until all Windows clients move to v2.
  if target_release.audience_key = 'boys' then
    update public.windows_audio_settings
    set active_release_id = p_release_id,
        default_profile_key = selected_default_profile,
        updated_by = auth.uid()
    where id = 1;
  end if;

  insert into public.windows_audio_audit_log (
    actor_type, action, entity_type, entity_id, details
  ) values (
    'programmer', 'release_published', 'audio_release', p_release_id::text,
    jsonb_build_object(
      'audience_key', target_release.audience_key,
      'version_number', target_release.version_number,
      'guidance_pool_size', selected_count
    )
  );

  return target_release;
end;
$$;

create or replace function public.get_school_audio_preference(p_school_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  school_record record;
  audience text;
  channel_record public.windows_audio_channels;
  profile_record public.windows_school_audio_profiles;
  release_record public.windows_audio_releases;
  effective_profile text;
  rotation jsonb;
  guidance_titles jsonb;
begin
  select school_name, school_slug, school_type, is_active
  into school_record
  from public.schools
  where school_slug = p_school_slug
  limit 1;

  if school_record.school_slug is null then
    return jsonb_build_object('available', false, 'message', 'المدرسة غير موجودة');
  end if;

  audience := public.windows_school_audience(p_school_slug);
  select * into channel_record
  from public.windows_audio_channels
  where audience_key = audience;

  select * into profile_record
  from public.windows_school_audio_profiles
  where school_slug = p_school_slug;

  effective_profile := coalesce(profile_record.profile_key, channel_record.default_profile_key, 'end_only');

  if channel_record.active_release_id is not null then
    select * into release_record
    from public.windows_audio_releases
    where id = channel_record.active_release_id
      and status = 'published';
  end if;

  rotation := case
    when release_record.id is null then jsonb_build_object('available', false)
    else public.windows_audio_rotation(release_record.manifest)
  end;

  select coalesce(
    jsonb_agg(
      coalesce(release_record.manifest -> 'assets' -> selected.asset_key ->> 'title_ar', selected.asset_key)
      order by selected.position
    ),
    '[]'::jsonb
  )
  into guidance_titles
  from jsonb_array_elements_text(
    coalesce(rotation -> 'selected_asset_keys', '[]'::jsonb)
  ) with ordinality selected(asset_key, position);

  return jsonb_build_object(
    'available', true,
    'school_name', school_record.school_name,
    'school_slug', school_record.school_slug,
    'school_active', school_record.is_active,
    'audience_key', audience,
    'profile_key', effective_profile,
    'is_customized', profile_record.school_slug is not null,
    'updated_source', profile_record.updated_source,
    'profile_updated_at', profile_record.updated_at,
    'release_available', release_record.id is not null,
    'release_id', release_record.id,
    'release_version', release_record.version_number,
    'release_title', release_record.title,
    'weekly_guidance', rotation,
    'weekly_guidance_titles', guidance_titles
  );
end;
$$;

create or replace function public.update_school_audio_preference(
  p_school_slug text,
  p_admin_code text,
  p_profile_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_record record;
  result jsonb;
begin
  if p_profile_key not in ('end_only', 'start_and_end') then
    return jsonb_build_object('success', false, 'message', 'النظام الصوتي غير صالح');
  end if;

  select school_slug, school_name, is_active
  into school_record
  from public.schools
  where school_slug = p_school_slug
    and admin_code is not null
    and btrim(admin_code) = btrim(coalesce(p_admin_code, ''))
  limit 1;

  if school_record.school_slug is null then
    return jsonb_build_object('success', false, 'message', 'رمز إدارة المدرسة غير صحيح');
  end if;
  if not coalesce(school_record.is_active, false) then
    return jsonb_build_object('success', false, 'message', 'المدرسة موقوفة حاليًا');
  end if;

  insert into public.windows_school_audio_profiles (
    school_slug, profile_key, updated_by, updated_at,
    updated_source, manager_updated_at
  ) values (
    p_school_slug, p_profile_key, null, now(),
    'school_manager', now()
  )
  on conflict (school_slug) do update
  set profile_key = excluded.profile_key,
      updated_by = null,
      updated_at = now(),
      updated_source = 'school_manager',
      manager_updated_at = now();

  insert into public.windows_audio_audit_log (
    actor_type, action, school_slug, entity_type, entity_id, details
  ) values (
    'school_manager', 'school_profile_changed', p_school_slug,
    'school_audio_profile', p_school_slug,
    jsonb_build_object('profile_key', p_profile_key)
  );

  result := public.get_school_audio_preference(p_school_slug);
  return result || jsonb_build_object(
    'success', true,
    'message', 'تم حفظ النظام الصوتي للمدرسة'
  );
end;
$$;

create or replace function public.get_windows_audio_bootstrap(p_school_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  audience text;
  channel_record public.windows_audio_channels;
  release_record public.windows_audio_releases;
  profile_record public.windows_school_audio_profiles;
  selected_profile text;
  release_assets jsonb;
  active_campaigns jsonb;
  rotation jsonb;
  school_date date;
begin
  audience := public.windows_school_audience(p_school_slug);
  if audience is null then
    return jsonb_build_object('available', false, 'reason', 'school_not_found');
  end if;

  select * into channel_record
  from public.windows_audio_channels
  where audience_key = audience;

  if channel_record.active_release_id is null then
    return jsonb_build_object(
      'available', false,
      'reason', 'audience_release_not_published',
      'audience_key', audience
    );
  end if;

  select * into release_record
  from public.windows_audio_releases
  where id = channel_record.active_release_id
    and status = 'published'
    and audience_key = audience;

  if release_record.id is null then
    return jsonb_build_object('available', false, 'reason', 'published_release_not_found');
  end if;

  select * into profile_record
  from public.windows_school_audio_profiles
  where school_slug = p_school_slug;

  selected_profile := coalesce(
    profile_record.profile_key,
    channel_record.default_profile_key,
    'end_only'
  );
  school_date := (now() at time zone 'Asia/Muscat')::date;
  rotation := public.windows_audio_rotation(release_record.manifest, school_date);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'asset_key', asset.asset_key,
        'kind', asset.kind,
        'category', asset.category,
        'title_ar', asset.title_ar,
        'storage_bucket', 'windows-audio',
        'storage_path', asset.storage_path,
        'mime_type', asset.mime_type,
        'file_size_bytes', asset.file_size_bytes,
        'duration_seconds', asset.duration_seconds,
        'checksum_sha256', asset.checksum_sha256,
        'sort_order', asset.sort_order
      ) order by asset.kind, asset.sort_order, asset.asset_key
    ),
    '[]'::jsonb
  ) into release_assets
  from public.windows_audio_assets asset
  where asset.release_id = release_record.id
    and asset.is_active;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', campaign.id,
        'title', campaign.title,
        'audience_key', campaign.audience_key,
        'play_slot', campaign.play_slot,
        'starts_on', campaign.starts_on,
        'ends_on', campaign.ends_on,
        'storage_bucket', 'windows-audio',
        'storage_path', campaign.storage_path,
        'file_name', campaign.file_name,
        'mime_type', campaign.mime_type,
        'file_size_bytes', campaign.file_size_bytes,
        'duration_seconds', campaign.duration_seconds,
        'checksum_sha256', campaign.checksum_sha256,
        'max_plays_per_day', campaign.max_plays_per_day
      ) order by campaign.starts_on, campaign.created_at
    ),
    '[]'::jsonb
  ) into active_campaigns
  from public.windows_audio_campaigns campaign
  where campaign.is_active
    and campaign.audience_key in ('all', audience)
    and school_date between campaign.starts_on and campaign.ends_on;

  return jsonb_build_object(
    'available', true,
    'school_slug', p_school_slug,
    'audience_key', audience,
    'release_id', release_record.id,
    'version_number', release_record.version_number,
    'published_at', release_record.published_at,
    'profile_key', selected_profile,
    'profile_source', coalesce(profile_record.updated_source, 'audience_default'),
    'manifest', release_record.manifest,
    'weekly_guidance', rotation,
    'assets', release_assets,
    'campaigns', active_campaigns
  );
end;
$$;

revoke all on function public.windows_school_audience(text) from public;
grant execute on function public.windows_school_audience(text) to anon, authenticated;

revoke all on function public.windows_audio_rotation(jsonb, date) from public;
grant execute on function public.windows_audio_rotation(jsonb, date) to anon, authenticated;

revoke all on function public.publish_windows_audio_release(uuid) from public;
grant execute on function public.publish_windows_audio_release(uuid) to authenticated;

revoke all on function public.get_school_audio_preference(text) from public;
grant execute on function public.get_school_audio_preference(text) to anon, authenticated;

revoke all on function public.update_school_audio_preference(text, text, text) from public;
grant execute on function public.update_school_audio_preference(text, text, text) to anon, authenticated;

revoke all on function public.get_windows_audio_bootstrap(text) from public;
grant execute on function public.get_windows_audio_bootstrap(text) to anon, authenticated;

commit;
